<?php
namespace ParrotDb\Core;



/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-18 at 17:07:28.
 */
class DBLockTest  extends \PHPUnit_Framework_TestCase
{
    

    public function tearDown()
    {
        PSessionFactory::closeSession(dirname(__FILE__) . "/pdb/Locktest");
    }


    public function testLockFail() {

        $this->expectException(PException::class);

        PSessionFactory::createSession(dirname(__FILE__) . "/pdb/Locktest", PSession::DB_FEATHER);
        PSessionFactory::createSession(dirname(__FILE__) . "/pdb/Locktest", PSession::DB_FEATHER);
    }

    public function testLockSucceed() {

        PSessionFactory::createSession(dirname(__FILE__) . "/pdb/Locktest", PSession::DB_FEATHER);
    }

 
}
