<?php
namespace ParrotDb\Core;

use ParrotDb\Datastructures\NaturalTreeArray;
use ParrotDb\Datastructures\NaturalTreeVirtArray;




/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-18 at 17:07:28.
 */
class NaturalTreeTest  extends \PHPUnit_Framework_TestCase
{
    
     /**
     * @var PPersistanceManager
     */
    protected $pm;
    
    protected $session;
    

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (file_exists(dirname(__FILE__) . "/test2.tree")) {
            unlink(dirname(__FILE__) . "/test2.tree");
        }

        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        if (file_exists(dirname(__FILE__) . "/test2.tree")) {
            unlink(dirname(__FILE__) . "/test2.tree");
        }
    }
    


    public function testNaturalTreeArray() {

    $tree = new NaturalTreeArray();

    $tree->add(15, 15);
    $tree->add(39, 39);
    $tree->add(3, 3);
    $tree->add(27, 27);
    $tree->add(1, 1);
    $tree->add(14, 14);

    $this->assertEquals("15,3,39,1,14,27,", $tree->printTree(6));
}

    public function testVirtArrNatTree() {

        $tree = new NaturalTreeVirtArray("test2.tree");

        $tree->add(15, 15);
        $tree->add(39, 39);
        $tree->add(3, 3);
        $tree->add(27, 27);
        $tree->add(1, 1);
        $tree->add(14, 14);

        $this->assertEquals("15,3,39,1,14,27,", $tree->printTree(6));
    }


}
