<?php
namespace ParrotDb\Query\LotB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-25 at 14:02:18.
 */
class ParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Parser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Parser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ParrotDb\Query\LotB\Parser::parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
    
    /**
     * @covers ParrotDb\Query\LotB\Parser::parse
     * @todo   Implement testParse().
     */
    public function testSplitGroup()
    {
        
        $exploded[] = "(";
        $exploded[] = "a";
        $exploded[] = "=";
        $exploded[] = '"b"';
        $exploded[] = ")";
        $exploded[] = "or";
        $exploded[] = "(";
        $exploded[] = "b";
        $exploded[] = "=";
        $exploded[] = '"a"';
        $exploded[] = ")";
        
        $result = $this->object->splitGroup($exploded);
        
        $grouping[] = array("(", "a", "=", '"b"', ")");
        $grouping[] = array("(", "b", "=", '"a"', ")");
        
        $this->assertEquals($grouping, $result);
        
        
    }
}
