<?php

namespace ParrotDb\Persistence\Xml;

use \ParrotDb\Core\ClassMapper;
use \ParrotDb\Core\PSessionFactory;
use \ParrotDb\Core\ObjectMapper;


require_once("../Author.php");
require_once("../Publication.php");

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-27 at 21:39:56.
 */
class XmlFileManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var XmlFileManager
     */
    protected $fileManager;
    
    protected $pm;
    
    protected $session;
    
    protected $serializer;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->fileManager = new XmlFileManager;
        $this->session = PSessionFactory::createSession("Testfile.db");
        $this->pm = $this->session->createPersistenceManager();
        $this->serializer = new XmlSerializer;
    }
    
    

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    private function createTestAuthor() {
        $author = new \Author("Mr Satan", 53);
        
        $author->allPublications = array();
        
        $author->allPublications[] = new \Publication("Lord Of The Rings");
        $author->allPublications[] = new \Publication("Star Wars");
        
        $author->orderedPublications[17] = new \Publication("Lord Of The Rings");
        $author->orderedPublications[21] = new \Publication("Star Wars");
        $author->nestedPublications = array();
        
        $author->size = 175;
        
        return $author;
    }

    /**
     * @covers ParrotDb\Persistence\Xml\XmlFileManager::storeObject
     * @todo   Implement testStoreObject().
     */
    public function testStoreObject() {
            
        $author = $this->createTestAuthor();
        $objectMapper = new ObjectMapper($this->session);

        $oid = $objectMapper->makePersistanceReady($author);
        $obj = null;
        foreach ($objectMapper->getOIdToPhpId() as $pObj) {
            if ($pObj->getObjectId()->getId() == $oid->getId()) {
                $obj = $pObj;
                break;
            }
        }

        $this->fileManager->storeObject($obj);
    
    }

}
