<?php

namespace ParrotDb\Persistence\Xml;

use \ParrotDb\Core\ClassMapper;
use \ParrotDb\Core\PSessionFactory;
use \ParrotDb\Core\ObjectMapper;


require_once("../Author.php");
require_once("../Publication.php");

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-27 at 13:49:11.
 */
class XmlSerializerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var XmlSerializer
     */
    protected $object;
    
    protected $pm;
    
    protected $session;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->session = PSessionFactory::createSession("Testfile.db");
        $this->pm = $this->session->createPersistenceManager();
        $this->serializer = new XmlSerializer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    private function createTestAuthor() {
        $author = new \Author("Mr Satan", 53);
        
        $author->allPublications = array();
        
        $author->allPublications[] = new \Publication("Lord Of The Rings");
        $author->allPublications[] = new \Publication("Star Wars");
        
        $author->orderedPublications[17] = new \Publication("Lord Of The Rings");
        $author->orderedPublications[21] = new \Publication("Star Wars");
        $author->nestedPublications = array();
        
        $author->size = 175;
        
        return $author;
    }

    /**
     * @covers ParrotDb\Persistence\Xml\XmlSerializer::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerializeClass() {
        
        $author = $this->createTestAuthor();
        $classMapper = new ClassMapper();
        $objectMapper = new ObjectMapper($this->session);
        
        $expected = "<?xml version=\"1.0\"?>\n"
         . "<class>"
         . "<name>Author</name>"
         . "<fields>"
         . "<field>name</field>"
         . "<field>age</field>"
         . "<field>size</field>"
         . "<field>publication</field>"
         . "<field>allPublications</field>"
         . "<field>orderedPublications</field>"
         . "<field>nestedPublications</field>"
         . "<field>partner</field>"
         . "<field>nationality</field>"
         . "<field>bla</field>"
         . "<field>testAttribute</field>"
         . "</fields>"
         . "<superclasses>"
         . "<superclass>Person</superclass>"
         . "<superclass>Human</superclass>"
         . "</superclasses>"
         . "</class>\n";
        
        $pClass = $classMapper->createClass($author);
        $xml = new \DOMDocument;
//        $is = $this->serializer->serializeClass($pClass, $xml);
//
//        
        $class = $this->serializer->serializeClass($classMapper->createClass($author), $xml);
        $xml->appendChild($class);
        $this->assertEquals($expected, $xml->saveXML());
        $oid = $objectMapper->makePersistanceReady($author);
        $obj = null;
        foreach ($objectMapper->getOIdToPhpId() as $pObj) {
            if ($pObj->getObjectId()->getId() == $oid->getId()) {
                $obj = $pObj;
                break;
            }
        }
            
 
        $exp = "<?xml version=\"1.0\"?>\n"
         . "<object>"
            . "<id>0</id>"
            . "<attributes>"
                . "<name>Mr Satan</name>"
                . "<age>53</age>"
                . "<size>175</size>"
                . "<publication/>"
                . "<attribute>"
                    . "<name>allPublications</name>"
                    . "<value>"
                        . "<array>"
                            . "<array>"
                                . "<elem>"
                                    . "<key>0</key>"
                                    . "<value>"
                                        . "<objectId>1</objectId>"
                                    . "</value>"
                                . "</elem>"
                                . "<elem>"
                                    . "<key>1</key>"
                                    . "<value>"
                                        . "<objectId>2</objectId>"
                                    . "</value>"
                                . "</elem>"
                            . "</array>"
                        . "</array>"
                    . "</value>"
                . "</attribute>"
                . "<attribute>"
                    . "<name>orderedPublications</name>"
                    . "<value>"
                        . "<array>"
                            . "<array>"
                                . "<elem>"
                                    . "<key>17</key>"
                                    . "<value>"
                                        . "<objectId>3</objectId>"
                                    . "</value>"
                                . "</elem>"
                                . "<elem>"
                                    . "<key>21</key>"
                                    . "<value>"
                                    .    "<objectId>4</objectId>"
                                    . "</value>"
                                . "</elem>"
                            . "</array>"
                        . "</array>"
                    . "</value>"
                . "</attribute>"
                . "<attribute>"
                    . "<name>nestedPublications</name>"
                    . "<value>"
                        . "<array>"
                            . "<array/>"
                        . "</array>"
                    . "</value>"
                . "</attribute>"
                . "<attribute>"
                    . "<name>partner</name>"
                    . "<value>"
                        . "<id>"
                            . "<objectId>0</objectId>"
                        . "</id>"
                    . "</value>"
                . "</attribute>"
                . "<nationality>german</nationality>"
                . "<bla>blaBla</bla>"
                . "<testAttribute>test</testAttribute>"
            . "</attributes>"
         . "</object>\n";

        $xml = new \DOMDocument;
        $this->serializer->setDomDocument($xml);
        $object = $this->serializer->serialize($obj);
        $xml->appendChild($object);
        $os = $xml->saveXML();
//               echo "###" . $os;
//   
        $this->assertEquals($exp, $os);
        
 

    }

}
